name: Deploy Jupyter Notebooks as HTML

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Convert Notebooks to HTML
        run: |
          mkdir html
          for notebook in notebooks/*.ipynb; do
            jupyter nbconvert --to html $notebook --output-dir html --execute --allow-errors
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          publish_branch: gh-pages  # Target branch for HTML files
